### ISSUE TITLE
Multilingual abstracts missing xml:lang attributes

### ISSUE THREAD

**Issue by kaitlinnewson** [asmecher/jatsTemplate#1]
Hi @asmecher, I've gotten some feedback from our metadata librarian (@karaleighh) on this plugin, and one issue noted was the following:

It would be ideal if abstracts with multiple languages always had the appropriate xml:lang attribute. This are missing in the sample data - the french abstract is provided as a second paragraph, still tagged as EN.. Ex (from WYAJ).

```
<abstract xml:lang="en">
<p>Third World Approaches to International Law [TWAIL] constitutes a
significant method of analysis of contemporary international law.
TWAIL as a methodological framework continues the tradition of
critical scholarship ....</p>
<p> </p>
<p>Le mouvement Third World Approaches to International Law (TWAIL)
constitue une importante méthode d’analyse du droit international
contemporain. ......</p>
</abstract>
```

(Tested with: https://wyaj.uwindsor.ca/index.php/WYAJ/oai?verb=ListRecords&metadataPrefix=jats)

**Comment by asmecher** [comment]
@kaitlinnewson, I suspect that both the English and French abstracts have been entered into the English abstract field together, rather than using separate English and French fields. Can you check this?

**Comment by kaitlinnewson** [comment]
@asmecher Looks like you're right, and the journal hasn't consistently used the french abstracts. Closing.
